name: Deploy GoCyberChef to GitHub Pages

on:
  push:
    branches:
      - main # Adjust if your default/production branch is different

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21' # Specify your desired Go version (e.g., '1.21', '1.22', or '1.x')

      - name: Build WASM
        run: |
          echo "Setting GOOS=js and GOARCH=wasm"
          export GOOS=js
          export GOARCH=wasm
          echo "Building main.wasm..."
          go build -v -o main.wasm main.go
          echo "Build complete. Files in current directory:"
          ls -la
        # The -v flag in go build shows package names as they are compiled.
        # main.wasm will be created in the root directory.

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Path to the directory to upload. 
          # The root directory contains index.html and all other necessary files, including the newly built main.wasm.
          path: '.'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
